
spring:
   datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password: root

   jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MYSQL8Dialect
